### PR TITLE
Type 'yo ho:ho' to generate and modify your ho.json

### PR DESCRIPTION
**Pull request by shurickz**
Adding new commands to ho.json using environment lookup for available generators

### CODE REVIEW

**Comment by stylesuxx** [comment]
Thank you for your submission - very appreciated.
I will look through it in the next couple of days - but will most probably merge it, just by the name of the command :-)

**Comment by shurickz** [comment]
Thx =)
Feel free to make suggestions or modify something in my code - I'm not very experienced in nodejs dev, so probably there are some places which could be done better )

**Comment by stylesuxx** [comment]
- Is there a reason you use the _deep-extend_ module instead of __extend_ from _util_?
  
  ``` JS
  var extend = require('util')._extend;
  var original = { one: 'one' };
  var append = { two: 'two' };
  
  extend(original, append);
  // original = { one: 'one', two: 'two' }
  ```
  
  This way we would not need to pull in new dependencies.
- Please also add a contributers section to _package.json_ and add yourself.
- For sake of style consistency it would be cool if you could change sections like so:
  
  ``` JS
  var generators = require('yeoman-generator'),
      environment = require('yeoman-environment'),
      extend = require('deep-extend');
  ```
  
  to
  
  ``` JS
  var generators = require('yeoman-generator');
  var environment = require('yeoman-environment');
  var extend = require('deep-extend');
  ```
  
  This is just a personal preference, since it makes it easier to remove element without needing to adapt semicolons if for example the last var is removed.
- You do not need to declare variables before using them, so instead of
  
  ``` JS
  // snip START
  
         var result = {},
             pathToHo,
             ho;
  
         result[this.name] = {
             generator: this.gen,
             subgen: this.subgen,
             parameters: this.params
         };
  
         pathToHo = this.destinationPath('ho.json');
  
         ho = this.fs.readJSON(pathToHo, {});
  
  // snip END
  ```
  
  I would suggest:
  
  ``` JS
  // snip START
  
         var result = {};
         result[this.name] = {
             generator: this.gen,
             subgen: this.subgen,
             parameters: this.params
         };
  
         var pathToHo = this.destinationPath('ho.json');
  
         var ho = this.fs.readJSON(pathToHo, {});
  
  // snip END
  ```
- Adding a test would be very cool, although I can do this when I actually try out the code, which I hope I will have time for later today.

Other thatn that :+1: - Thank you very much.

**Comment by shurickz** [comment]
> Is there a reason you use the deep-extend module instead of _extend from util?

Now there is no need to use any kind of extend at all. Initially I thought about adding all available generators but then I understood that there could be too many options, and also there would be difficulties with adding names for all of them. In current implementation It's possible to use 

`ho[this.name] = { ... }`

> For sake of style consistency it would be cool if you could change sections

Completely agree, I've just used default config for jslint which suggested that. I'll try to think about customizing my jslint checks

> Adding a test would be very cool

I'll try to think about it, i didn't learn before about testing prompts, good time to do this )

Thanks for CR, i'll try to push fixes asap

**Comment by shurickz** [comment]
@stylesuxx CR fixed, check this please

**Comment by stylesuxx** [comment]
Looking good, thank you.

I will now merge it and try it out. I'll release a new version to NPM in next couple of days.

**Pull request merged**
